### ISSUE TITLE
Note about xcode 13 failures

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-xcuitest-driver#1312]
I observed the below error in tvOS test in ruby_lib_core test suite, but others seem good. The below is Apple side stuff. (Not WDA specific thing)
```
[Xcode] 2021-06-08 21:29:46.890282-0700 WebDriverAgentRunner_tvOS-Runner[43582:693623] [BackgroundTask] Background Task 1 ("Called by UIKitCore, from -[UIApplication _deactivateForReason:notify:]"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
[Xcode]
```

---

Haven't checked, but the result of the profiler name changed?

```
  1) XCUITestDriver - performance
       record performance metrics
         should return recorded trace file on stop:
     {"message":"[execute(\"mobile: stopPerfRecord\",{\"profileName\":\"Time Profiler\"})] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: There is no .trace file found for performance profile 'Time Profiler' and device 53FC6B27-9ABE-4FC6-B69D-E34F069363DC. Make sure the selected profile is supported on this device","status":13,"cause":{"s...
  Error: [execute("mobile: stopPerfRecord",{"profileName":"Time Profiler"})] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: There is no .trace file found for performance profile 'Time Profiler' and device 53FC6B27-9ABE-4FC6-B69D-E34F069363DC. Make sure the selected profile is supported on this device
      at exports.newError (node_modules/wd/lib/utils.js:152:13)
      at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/wd/lib/callbacks.js:94:19
      at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/wd/lib/webdriver.js:205:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1083:12)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

---

  1) XCUITestDriver - element(s)
       interactions
         text fields
           "before each" hook for "should type in the text field":
     {"message":"[execute(\"mobile: scroll\",{\"element\":{\"ELEMENT\":\"8A000000-0000-0000-6ECB-000000000000\"},\"toVisible\":true})] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 480000ms exceeded","status":13,"cause":{"status":13,"value":{"message":"An unknown se...
  Error: [execute("mobile: scroll",{"element":{"ELEMENT":"8A000000-0000-0000-6ECB-000000000000"},"toVisible":true})] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 480000ms exceeded
      at exports.newError (node_modules/wd/lib/utils.js:152:13)
      at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/wd/lib/callbacks.js:94:19
      at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/wd/lib/webdriver.js:205:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1083:12)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

  2) XCUITestDriver - find
       duplicate text field
         "after all" hook for "should find only one element per secure text field":
     {"message":"[execute(\"mobile: scroll\",{\"element\":{\"ELEMENT\":\"8A000000-0000-0000-1FCC-000000000000\"},\"toVisible\":true})] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 480000ms exceeded","status":13,"cause":{"status":13,"value":{"message":"An unknown se...
  Error: [execute("mobile: scroll",{"element":{"ELEMENT":"8A000000-0000-0000-1FCC-000000000000"},"toVisible":true})] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 480000ms exceeded
      at exports.newError (node_modules/wd/lib/utils.js:152:13)
      at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/wd/lib/callbacks.js:94:19
      at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/wd/lib/webdriver.js:205:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1083:12)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

  3) XCUITestDriver - find
       by predicate string
         should find invisible elements:

      AssertionError: expected [] to have a length above 0 but got 0
      + expected - actual

      at Context.<anonymous> (test/functional/basic/find-e2e-specs.js:336:30)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  4) XCUITestDriver - find
       by predicate string
         should find elements with widths above 0:

      AssertionError: expected [] to have a length above 0 but got 0
      + expected - actual

      at Context.<anonymous> (test/functional/basic/find-e2e-specs.js:341:30)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  5) XCUITestDriver - gestures
       dynamic gestures
         should scroll using touch actions:
     {"message":"[element.isDisplayed()] Error response status: 10, , StaleElementReference - An element command failed because the referenced element is no longer attached to the DOM. Selenium error: The previously found element \"\"Web View\" StaticText\" is not present in the current view anymore. Make sure the application UI has the expected state. You could also try to switch the binding strategy using the 'boundElementsByIndex' setting for the element lookup. Original error: No matches found fo...
  Error: [element.isDisplayed()] Error response status: 10, , StaleElementReference - An element command failed because the referenced element is no longer attached to the DOM. Selenium error: The previously found element ""Web View" StaticText" is not present in the current view anymore. Make sure the application UI has the expected state. You could also try to switch the binding strategy using the 'boundElementsByIndex' setting for the element lookup. Original error: No matches found for Identity Binding from input {(
      StaticText, {{16.0, 628.0}, {76.0, 20.5}}, label: 'Web View'
  )}
      at exports.newError (node_modules/wd/lib/utils.js:152:13)
      at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/wd/lib/callbacks.js:94:19
      at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/wd/lib/webdriver.js:205:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1083:12)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

-----

  15 passing (8m)
  1 failing

  1) XCUITestDriver - performance
       record performance metrics
         should return recorded trace file on stop:
     {"message":"[execute(\"mobile: stopPerfRecord\",{\"profileName\":\"Time Profiler\"})] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: There is no .trace file found for performance profile 'Time Profiler' and device 53FC6B27-9ABE-4FC6-B69D-E34F069363DC. Make sure the selected profile is supported on this device","status":13,"cause":{"s...
  Error: [execute("mobile: stopPerfRecord",{"profileName":"Time Profiler"})] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: There is no .trace file found for performance profile 'Time Profiler' and device 53FC6B27-9ABE-4FC6-B69D-E34F069363DC. Make sure the selected profile is supported on this device
      at exports.newError (node_modules/wd/lib/utils.js:152:13)
      at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/wd/lib/callbacks.js:94:19
      at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/wd/lib/webdriver.js:205:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1083:12)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

---

```
  1) Safari - basics -
       init
         should start a session with default init:
     Error: [init({"browserName":"Safari","nativeWebTap":false,"platformName":"iOS","platformVersion":"15.0","deviceName":"iPhone 8","automationName":"XCUITest","launchWithIDB":false,"noReset":true,"maxTypingFrequency":30,"clearSystemFiles":true,"showXcodeLog":false,"wdaLaunchTimeout":240000,"wdaConnectionTimeout":480000,"useNewWDA":true,"webviewConnectTimeout":30000,"simulatorStartupTimeout":240000})] The environment you requested was unavailable.
An unknown server-side error occurred while processing the command. Original error: Could not navigate to webview; there are none!
      at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/wd/lib/webdriver.js:157:15
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1083:12)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

  2) safari - windows and frames
       without safariAllowPopups
         "before all" hook for "should not be able to open js popup windows":
     Error: Timeout of 240000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/kazuaki/GitHub/appium-xcuitest-driver/build/test/functional/web/safari-window-e2e-specs.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  3) safari - windows and frames
       with safariAllowPopups
         "before all" hook in "with safariAllowPopups":
     Error: [init({"safariInitialUrl":"http://localhost:4994/test/guinea-pig","safariAllowPopups":true,"nativeWebTap":true,"browserName":"Safari","platformName":"iOS","platformVersion":"15.0","deviceName":"iPhone 8","automationName":"XCUITest","launchWithIDB":false,"noReset":true,"maxTypingFrequency":30,"clearSystemFiles":true,"showXcodeLog":false,"wdaLaunchTimeout":240000,"wdaConnectionTimeout":480000,"useNewWDA":true,"webviewConnectTimeout":30000,"simulatorStartupTimeout":240000})] The environment you requested was unavailable.
A new session could not be created. Details: Cannot create a new session while one is in progress
      at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/wd/lib/webdriver.js:157:15
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1083:12)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

  4) iPhone 6 -
       "before all" hook for "should be able to tap on an element":
     Error: [init({"deviceName":"iPhone 6","safariInitialUrl":"http://localhost:4994/test/guinea-pig","nativeWebTap":true,"browserName":"Safari","platformName":"iOS","platformVersion":"15.0","automationName":"XCUITest","launchWithIDB":false,"noReset":true,"maxTypingFrequency":30,"clearSystemFiles":true,"showXcodeLog":false,"wdaLaunchTimeout":240000,"wdaConnectionTimeout":480000,"useNewWDA":true,"webviewConnectTimeout":30000,"simulatorStartupTimeout":240000})] The environment you requested was unavailable.
An unknown server-side error occurred while processing the command. Original error: Could not create simulator with name 'appiumTest-99125925-DA80-4120-BA76-FB9385CA699B-iPhone 6', device type id 'iPhone 6', with runtime ids 'com.apple.CoreSimulator.SimRuntime.iOS-15-0'
      at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/wd/lib/webdriver.js:157:15
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1083:12)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

  5) iPad Simulator -
       with tabs -
         should be able to tap on an element after scrolling, when the url bar is present:
     {"message":"[elementByAccessibilityId(\"URL\")] Error response status: 7, , NoSuchElement - An element could not be located on the page using the given search parameters. Selenium error: An element could not be located on the page using the given search parameters.","status":7,"cause":{"status":7,"value":{"message":"An element could not be located on the page using the given search parameters."},"sessionId":"3f4fd063-c2a7-42c0-8095-06a874e8fdc2"},"jsonwire-error":{"status":7,"summary":"NoSuchEle...
  Error: [elementByAccessibilityId("URL")] Error response status: 7, , NoSuchElement - An element could not be located on the page using the given search parameters. Selenium error: An element could not be located on the page using the given search parameters.
      at exports.newError (node_modules/wd/lib/utils.js:152:13)
      at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/wd/lib/callbacks.js:94:19
      at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/wd/lib/webdriver.js:205:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1083:12)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by KazuCocoa** [comment]
`mobile: scroll` did not stop on Text Field cell, so some tests failed.
Checking safari stuff

**Comment by mykola-mokhnach** [comment]
> iPhone 6

This device is probably not supported anymore with Xcode13. We should bump the version to iPhone X or iPhone 12

**Comment by KazuCocoa** [comment]
For safari.
It seems Safari itself behaves differently from older ones.
`safariAllowPopups` worked expectedly, but Safari did not return a response until the popup disappears.
I should dig this behavior more, but as Appium, Xcode 13 x iOS 15 has no critical issue for now.


Btw, I got WDA process launching failure a few times because of no id found error. It was random failure, so it seems Xcode beta has random launching a process issue.

--

yea, > iPhone versions

**Comment by KazuCocoa** [comment]
ah, will take a look at the below error tomorrow, performance output.
This error happened in ruby_lib_core suite as well.


```
  1) XCUITestDriver - performance
       record performance metrics
         should return recorded trace file on stop:
     {"message":"[execute(\"mobile: stopPerfRecord\",{\"profileName\":\"Time Profiler\"})] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: There is no .trace file found for performance profile 'Time Profiler' and device 53FC6B27-9ABE-4FC6-B69D-E34F069363DC. Make sure the selected profile is supported on this device","status":13,"cause":{"s...
  Error: [execute("mobile: stopPerfRecord",{"profileName":"Time Profiler"})] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: There is no .trace file found for performance profile 'Time Profiler' and device 53FC6B27-9ABE-4FC6-B69D-E34F069363DC. Make sure the selected profile is supported on this device
      at exports.newError (node_modules/wd/lib/utils.js:152:13)
      at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/wd/lib/callbacks.js:94:19
      at /Users/kazuaki/GitHub/appium-xcuitest-driver/node_modules/wd/lib/webdriver.js:205:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1083:12)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by mykola-mokhnach** [comment]
Regarding the performance - earlier I was observing a similar issue when Apple removed/renamed one of available performance profiles. Perhaps, the same thing happens now, so we just need to provide any of supported names there

**Comment by jlipps** [comment]
great research @KazuCocoa!

**Comment by KazuCocoa** [comment]
- the path to `.trace` must exist. `/var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/T/202159-17608-16ohw0f.8mhy/`
- Even when I gave an existing device, the command returned no matched device. Then, I needed to type the device info. So, potentially finding a device does not work well for now.

```
% /usr/bin/xcrun xctrace record --device 8061DB85-D0FB-48CD-BA29-164B80881600 --template 'Time Profiler' --output /var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/T/202159-17608-16ohw0f.8mhy/appium_perf__Time_Profiler__1623304344308.trace --time-limit 300000ms --all-processes
No devices found matching 8061DB85-D0FB-48CD-BA29-164B80881600
Choose from the list of all devices:
== Devices ==
[0] kazu's MB pro (34DA2EBC-9EE6-578F-8C7B-0B73E536C926)

== Simulators ==
[1] Apple TV Simulator (15.0) (58FEEA80-9429-43F5-AF10-A73C78A3673E)
[2] Apple TV 4K Simulator (15.0) (1D164B9B-1ED2-4682-AAB5-C20455028AEF)
[3] Apple TV 4K (2nd generation) Simulator (15.0) (8C9FBAAD-DEAB-4C2C-A98D-FA39293FC754)
[4] Apple TV 4K (at 1080p) Simulator (15.0) (27F5CE73-9C3E-43FB-8B06-54542D593313)
[5] Apple TV 4K (at 1080p) (2nd generation) Simulator (15.0) (4C81C0A6-2655-4D95-A17B-73BD453F3625)
[6] appiumTest-E0CF23AE-BB7D-49AF-8ADA-D0327F2CC794-iPad (5th generation) Simulator (15.0) (B5A9B328-9F2A-40E7-BEE1-716A4869C014)
[7] appiumTest-EE0E4096-2049-4FB8-893D-BE361C0DBC1C-iPhone X Simulator (15.0) (52EAE2A4-99F1-44DA-8603-1B0879F2A9A1)
[8] create iPhone XS Simulator (12.0) (53FEEACA-3576-444F-89E4-D81A22849B80)
[9] iPad (5th generation) Simulator (11.4) (7F312B51-D03E-48E1-A671-B1FDFCDDDD4C)
[10] iPad (5th generation) Simulator (12.0) (47FE7084-F129-4CA3-B3CC-2C0C2E1F82A3)
[11] iPad (6th generation) Simulator (11.4) (EBB3D590-51DF-4FC3-AA63-DFBAB9DACCCD)
[12] iPad (6th generation) Simulator (12.0) (4E58AAA7-11FE-4F72-88E1-3D5B79B5E61E)
[13] iPad (8th generation) Simulator (15.0) (DB22FB2B-A13E-46E0-99D7-FA2D02B44E8E)
[14] iPad Air Simulator (11.4) (A32079BD-E64F-4D14-9638-E4E02A5ECCA2)
[15] iPad Air Simulator (12.0) (6A267561-2485-4F92-AC86-2463415C129D)
[16] iPad Air (3rd generation) Simulator (13.0) (3CB5EB53-F1BE-4C93-B497-AC510E84391A)
[17] iPad Air (4th generation) Simulator (15.0) (CC271898-63B0-47D2-8CA2-CC6056631906)
[18] iPad Air 2 Simulator (11.4) (3CA8D43E-1481-4C34-9434-C68BDFF01ECB)
[19] iPad Air 2 Simulator (12.0) (79FB4E67-ED1E-451F-BD90-C1916AE83566)
[20] iPad Pro (10.5-inch) Simulator (11.4) (B368433C-840B-4BFF-A10B-F52B6C6E7667)
[21] iPad Pro (10.5-inch) Simulator (12.0) (5091C494-1B1F-448B-AAA0-478204D4F4F4)
[22] iPad Pro (11-inch) Simulator (13.0) (0C17B54B-71CE-4D5E-A6C0-6CC0873C3F6A)
[23] iPad Pro (11-inch) (2nd generation) Simulator (15.0) (5A55BE04-57B8-4C88-90E6-42C86A2A2BDA)
[24] iPad Pro (11-inch) (3rd generation) Simulator (15.0) (70D8BACB-4773-4DFE-860A-CD799460A519)
[25] iPad Pro (12.9-inch) Simulator (11.4) (600B4F14-E077-44A6-852D-08B8C5621E75)
[26] iPad Pro (12.9-inch) Simulator (12.0) (790C0B4C-1526-4826-AA06-DFC34BA9750C)
[27] iPad Pro (12.9-inch) (2nd generation) Simulator (11.4) (FDC93770-1A09-44DB-8D9E-C0E3D068E7F9)
[28] iPad Pro (12.9-inch) (2nd generation) Simulator (12.0) (5F540393-A4B3-428B-A45C-0BFD1E374C9E)
[29] iPad Pro (12.9-inch) (3rd generation) Simulator (13.0) (E9974C7E-FEDF-4E8D-A65E-D5F770FC713F)
[30] iPad Pro (12.9-inch) (4th generation) Simulator (15.0) (1549301A-4B99-4078-AAF1-BF8AD20EB102)
[31] iPad Pro (12.9-inch) (5th generation) Simulator (15.0) (7C421609-2F19-4190-9976-36B13098D45A)
[32] iPad Pro (9.7-inch) Simulator (11.4) (62077F91-7EC7-4B2B-B991-56B598966732)
[33] iPad Pro (9.7-inch) Simulator (12.0) (0D98E5DD-FABF-48EB-8F4A-0B04A4C55C83)
[34] iPad Pro (9.7-inch) Simulator (13.0) (6E153CE0-CAC6-477F-AF80-324DF5E83CE0)
[35] iPad Pro (9.7-inch) Simulator (15.0) (F634092A-D016-42BF-8F10-3D7D585B48EC)
[36] iPhone 11 Simulator (13.0) (32571DFD-9F73-45ED-8268-239F156EC057)
[37] iPhone 11 Simulator (13.0) (219C22A6-9361-4FCD-9EA8-FC2A70EEDFE8)
[38] iPhone 11 Simulator (15.0) (8061DB85-D0FB-48CD-BA29-164B80881600)
[39] iPhone 11 Pro Simulator (13.0) (7ED58DC6-2C15-4E4B-8A18-03B45250C4E7)
[40] iPhone 11 Pro Simulator (15.0) (2F6EBB93-EDA7-453D-B30B-982996B54F2D)
[41] iPhone 11 Pro Max Simulator (13.0) (EDE7AD6C-6F3C-455E-82FE-BDE0CADEB957)
[42] iPhone 11 Pro Max Simulator (15.0) (FFF0D753-6563-461E-8A36-9DF32F7E0518)
[43] iPhone 12 Simulator (15.0) (BA4431B1-800B-441C-B3EB-1C911C5767A9)
[44] iPhone 12 Simulator (15.0) + Apple Watch Series 5 - 44mm (8.0) (8C1D5665-4AD9-4599-8253-5E4BC62AFC8F)
[45] iPhone 12 Pro Simulator (15.0) (E7F9F2F3-B9A4-49AA-A080-066A725FB236)
[46] iPhone 12 Pro Simulator (15.0) + Apple Watch Series 6 - 40mm (8.0) (B0F81085-1DC9-4D3E-BBCC-9F38087A7BCA)
[47] iPhone 12 Pro Max Simulator (15.0) (F07A2C2A-75B3-4F26-80F6-4660181D9295)
[48] iPhone 12 Pro Max Simulator (15.0) + Apple Watch Series 6 - 44mm (8.0) (FCAA52C6-8B12-449F-89F3-510766AF6A08)
[49] iPhone 12 mini Simulator (15.0) (FD596F10-29FC-4296-A06B-DDA4F72A4914)
[50] iPhone 12 mini Simulator (15.0) + Apple Watch Series 5 - 40mm (8.0) (A75873DA-BD45-4B48-986C-F51BCD87A02F)
[51] iPhone 5s Simulator (11.4) (824146C3-1D72-4AF9-B6DB-2F0E582A9279)
[52] iPhone 5s Simulator (12.0) (60F58F39-3BE0-43FC-82DB-01DE468BAB97)
[53] iPhone 6 Simulator (11.4) (44C3E400-CCC8-4FEC-8457-3B3CF93DFEFF)
[54] iPhone 6 Simulator (12.0) (7E9C7ED1-E371-487E-9FBE-3B6D3EAE72CE)
[55] iPhone 6 Plus Simulator (11.4) (1EEA9631-F2C7-4297-A84B-7597DE288E4C)
[56] iPhone 6 Plus Simulator (12.0) (0C7EB65C-2B9A-4D51-A72E-D664281E9730)
[57] iPhone 6s Simulator (11.4) (42285D86-539C-4113-9A16-8D74C84A4029)
[58] iPhone 6s Simulator (12.0) (90F69BDD-064C-4BA0-9704-2E44130DC611)
[59] iPhone 6s Plus Simulator (11.4) (B01EAFFB-7DE3-461B-AA6A-FCAA00361193)
[60] iPhone 6s Plus Simulator (12.0) (CE58C083-DCB1-455D-B1B6-C00AE7C17363)
[61] iPhone 7 Simulator (11.4) (F00689C4-31A1-4CFC-AB27-935631E54A73)
[62] iPhone 7 Simulator (12.0) (D52AA612-AC0B-4C01-AD9E-CE2DF44FCD78)
[63] iPhone 7 Plus Simulator (11.4) (1FED43B4-29AB-4E07-BA5D-6C04C3380311)
[64] iPhone 7 Plus Simulator (12.0) (F0731202-C3A9-46BF-B548-CBFC80DF31D3)
[65] iPhone 8 Simulator (11.4) (3CB9E12B-419C-49B1-855A-45322861F1F7)
[66] iPhone 8 Simulator (12.0) (8115F1D4-18F0-4161-835A-0D930A5C69E9)
[67] iPhone 8 Simulator (13.0) (54C95E00-7CF9-4623-A968-3C0605C609D9)
[68] iPhone 8 Simulator (15.0) (53FC6B27-9ABE-4FC6-B69D-E34F069363DC)
[69] iPhone 8 - 8100 Simulator (11.4) (01FAB8D7-FD25-4688-9057-1A36A44E9A93)
[70] iPhone 8 - 8101 Simulator (11.4) (5589BDEF-482C-431B-B699-2F0E968B17F8)
[71] iPhone 8 Plus Simulator (11.4) (34726ACE-F14C-493C-A963-CD83538821D7)
[72] iPhone 8 Plus Simulator (12.0) (5262F338-E4A7-445A-89FC-45E4123BE449)
[73] iPhone 8 Plus Simulator (13.0) (666A2C80-90B7-441E-95FF-EEB18A6A5FD2)
[74] iPhone 8 Plus Simulator (15.0) (D0B1B147-F3C0-4042-90C9-9EC8F0A5692B)
[75] iPhone SE Simulator (11.4) (597C5BA9-1A1C-4416-ADF0-CBBD0E0A3601)
[76] iPhone SE Simulator (12.0) (8EA5F438-5F1B-41CD-8172-48CD75E139C2)
[77] iPhone SE (2nd generation) Simulator (15.0) (95546041-FC39-4EF8-BFC1-C1B8AE41BBC5)
[78] iPhone X Simulator (11.4) (48BDBCA2-13B6-4ABF-BF9F-FA019B96008C)
[79] iPhone X Simulator (12.0) (64A22045-9B74-4BB1-861E-B6E6B6C7426C)
[80] iPhone XR Simulator (12.0) (0E8DC400-5E1F-4B70-912B-940A03F95CC9)
[81] iPhone XS Simulator (12.0) (ED0C78DE-6B62-46D4-9B3A-CCECF3726572)
[82] iPhone XS Max Simulator (12.0) (5D92EE75-62B6-4FDE-A2A9-ABA93BA87533)
[83] iPhone Xs Simulator (13.0) (66EEA439-EF9D-4848-BB5D-8075C88E6176)
[84] iPhone Xs Max Simulator (13.0) (6C5BAB8D-A345-40B9-90AE-59141BD6A19E)
[85] iPhone Xʀ Simulator (13.0) (F2839DB9-506E-4592-AC52-21EC21F967EF)
[86] iPod touch (7th generation) Simulator (15.0) (D74E36F8-C726-4632-BF53-BAAFEE8F47E1)
[87] new iPhone XS Max Simulator (12.0) (CF447F39-EB5B-47CB-995B-CDAB73842006)
Specify device [0-87]:
38
Starting recording with the Time Profiler template. Targeting All Processes. Time limit: 300000.0 ms
Ctrl-C to stop the recording
^CStopping recording...
Recording completed. Saving output file...
```

**Comment by KazuCocoa** [comment]
Basically the performance command raises an error code because of the above comment even when the device has the same uidi simulator. So, let's wait for Xcode improvements for now.

```
[HTTP] <-- POST /wd/hub/session/6e073c02-2a90-40fb-8d26-c1227c222c24/execute/sync 200 3472 ms - 14
[HTTP]
[debug] [Time Pr...@BA4431B1] [xctrace] No devices found matching BA4431B1-800B-441C-B3EB-1C911C5767A9
[debug] [Time Pr...@BA4431B1]
[Time Pr...@BA4431B1] Performance recording exited with error code 27, signal null
^C[Appium] Received SIGINT - shutting down
```

**Comment by mykola-mokhnach** [comment]
@KazuCocoa This looks like a bug in Xcode beta. Could you please report it to Apple?

**Comment by KazuCocoa** [comment]
Yup. I've reported it with https://github.com/appium/appium-xcuitest-driver/issues/1312#issuecomment-858332712 this example

**Comment by KazuCocoa** [comment]
The latest Xcode 13 beta 3 fixed the issue in performance.

**Comment by krishtoautomate** [comment]
This is not fixed in any beta builds.

Found issue with xcode not finding destination.

Issue is xcodebuild command will not work properly if same host machine is connected with more than 18-20 ios devices.
