### ISSUE TITLE
xcodebuild failed with code 70

### ISSUE THREAD

**Issue by joshrlesch** [appium/appium-xcuitest-driver#132]
I have built and ran `appium-xcuitest-driver` in the past, but pulled the lastest bits from master and getting an xcodebuild error.

I was able to clone WDA, and build through xcode
I was able to take the command from the driver logs and run it manually, but when kicking off an apoium session, xcodebuild fails

```
[iOSSim] Simulator booted in 19682ms
[XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Beginning test with command 'xcodebuild -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=BD897B5C-90C8-4A4D-9916-DDB7EC0DEDEF test' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[XCUITest] xcodebuild exited with code '70' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (lib/webdriveragent.js:214:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
 Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (lib/webdriveragent.js:214:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
[XCUITest] Shutting down WebDriverAgent
[XCUITest] Simulator log exited with code 'null'
[debug] [XCUITest] Resetting simulator
[debug] [XCUITest] Shutting down simulator
[debug] [iOSSim] Killing all iOS Simulators
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (lib/webdriveragent.js:214:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
[HTTP] <-- POST /wd/hub/session 500 2
```

**Comment by imurchie** [comment]
Since you're running from source, can you change `logXcodeOutput` to `true` [here](https://github.com/appium/appium-xcuitest-driver/blob/master/lib/webdriveragent.js#L129)? Then re-transpile (`gulp transpile`) and re-run?

**Comment by joshrlesch** [comment]
FYI, I first saw this when I install the 1.6 beta, so then tried the source of `appium-xcuitest-driver`. But after making that change, it seems the simulator being created isn't being seen by xcodebuild as an available sim.
```
[debug] [XCUITest] Beginning test with command 'xcodebuild -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=BD897B5C-90C8-4A4D-9916-DDB7EC0DEDEF test' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] ----------xcodebuild: error: Unable to find a destination matching the provided destination specifier:
       		{ id:BD897B5C-90C8-4A4D-9916-DDB7EC0DEDEF }

       	Available destinations for the "WebDriverAgentRunner" scheme:
       		{ platform:iOS Simulator, id:51E823D9-C5A0-4AB5-8FEC-4638BE03F324, OS:9.3, name:iPad 2 }
       		{ platform:iOS Simulator, id:82778BD1-7418-4532-8598-0B001125BEDA, OS:9.3, name:iPad Air }
       		{ platform:iOS Simulator, id:B9CCDF75-9090-4EB0-B68A-08E175849057, OS:9.3, name:iPad Air 2 }
       		{ platform:iOS Simulator, id:28DAAC8D-4F26-4F56-867A-E4C7B8D503E4, OS:9.3, name:iPad Pro }
       		{ platform:iOS Simulator, id:D02AD8E8-3D6C-4F19-A394-4D44425F036A, OS:9.3, name:iPad Retina }
       		{ platform:iOS Simulator, id:F3E36F6B-77D7-49E6-9FE5-1BA7E879AF67, OS:9.3, name:iPhone 4s }
       		{ platform:iOS Simulator, id:C4FCED2A-3636-4D52-A553-73FDA177FB62, OS:9.3, name:iPhone 5 }
       		{ platform:iOS Simulator, id:DFE73A44-4939-4C29-8D18-B35BA8560641, OS:9.3, name:iPhone 5s }
       		{ platform:iOS Simulator, id:C1C5E232-B196-49A6-BF65-DF5C4D693BCB, OS:9.3, name:iPhone 6 }
       		{ platform:iOS Simulator, id:F8CCB91D-079E-4543-853F-58DE6DE393CE, OS:9.3, name:iPhone 6 Plus }
       		{ platform:iOS Simulator, id:A1FB37B9-45B2-4214-9885-BBD914E5021F, OS:9.3, name:iPhone 6s }
       		{ platform:iOS Simulator, id:0B91A0E7-1C73-4452-A65E-2ED6B841127D, OS:9.3, name:iPhone 6s Plus }
--------
[XCUITest] xcodebuild: error: Unable to find a destination matching the provided destination specifier:
       		{ id:BD897B5C-90C8-4A4D-9916-DDB7EC0DEDEF }

       	Available destinations for the "WebDriverAgentRunner" scheme:
       		{ platform:iOS Simulator, id:51E823D9-C5A0-4AB5-8FEC-4638BE03F324, OS:9.3, name:iPad 2 }
       		{ platform:iOS Simulator, id:82778BD1-7418-4532-8598-0B001125BEDA, OS:9.3, name:iPad Air }
       		{ platform:iOS Simulator, id:B9CCDF75-9090-4EB0-B68A-08E175849057, OS:9.3, name:iPad Air 2 }
       		{ platform:iOS Simulator, id:28DAAC8D-4F26-4F56-867A-E4C7B8D503E4, OS:9.3, name:iPad Pro }
       		{ platform:iOS Simulator, id:D02AD8E8-3D6C-4F19-A394-4D44425F036A, OS:9.3, name:iPad Retina }
       		{ platform:iOS Simulator, id:F3E36F6B-77D7-49E6-9FE5-1BA7E879AF67, OS:9.3, name:iPhone 4s }
       		{ platform:iOS Simulator, id:C4FCED2A-3636-4D52-A553-73FDA177FB62, OS:9.3, name:iPhone 5 }
       		{ platform:iOS Simulator, id:DFE73A44-4939-4C29-8D18-B35BA8560641, OS:9.3, name:iPhone 5s }
       		{ platform:iOS Simulator, id:C1C5E232-B196-49A6-BF65-DF5C4D693BCB, OS:9.3, name:iPhone 6 }
       		{ platform:iOS Simulator, id:F8CCB91D-079E-4543-853F-58DE6DE393CE, OS:9.3, name:iPhone 6 Plus }
       		{ platform:iOS Simulator, id:A1FB37B9-45B2-4214-9885-BBD914E5021F, OS:9.3, name:iPhone 6s }
       		{ platform:iOS Simulator, id:0B91A0E7-1C73-4452-A65E-2ED6B841127D, OS:9.3, name:iPhone 6s Plus }

[XCUITest] Waiting for WebDriverAgent to start on device
[XCUITest] xcodebuild exited with code '70' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (lib/webdriveragent.js:214:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:192:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
 Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (lib/webdriveragent.js:214:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:192:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
[XCUITest] Shutting down WebDriverAgent
[XCUITest] Simulator log exited with code 'null'
[debug] [XCUITest] Resetting simulator
[debug] [XCUITest] Shutting down simulator
[debug] [iOSSim] Killing all iOS Simulators
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (lib/webdriveragent.js:214:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:192:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
[HTTP] <-- POST /wd/hub/session 500 37541 ms -
```

**Comment by imurchie** [comment]
Ah. Yes, the underlying system does not support iOS 9.2. It will only work for 9.3 and 10.

**Comment by joshrlesch** [comment]
I see you open https://github.com/appium/appium-xcuitest-driver/pull/139. Do you ever see wanting to run tests agains older iOS versions for regression? Or is this a limitation with apples framworks?

**Comment by imurchie** [comment]
I'm not sure if it is Apple or the framework we are using to access Apple that is the limiting force here. Older versions of iOS can be tested using the ios-driver (as they can in older versions of Appium).

**Comment by joshrlesch** [comment]
sounds good to me. Thanks
