### ISSUE TITLE
 Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'

### ISSUE THREAD

**Issue by romainlouvet** [appium/appium-xcuitest-driver#140]
when I run appium with this last commit https://github.com/appium/appium/commit/bf71e40206a59a405554ac94839782d94cb9c9a1

iOS 10 (real device) & Xcode 8

```
[XCUITest]
Testing failed:
	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.

[XCUITest] 	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'
** TEST FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
```

**Comment by yaphatak** [comment]
Do you like this when you open WebDriverAgent project https://github.com/appium/appium-xcuitest-driver/issues/106#issuecomment-243001378

**Comment by 03623170** [comment]
Well I did sign my WDA as described but somehow it still doesn't work
<img width="653" alt="bildschirmfoto 2016-09-16 um 15 23 38" src="https://cloud.githubusercontent.com/assets/7427925/18587370/fbfef084-7c21-11e6-9fd5-3418f684a196.png">

**Comment by yaphatak** [comment]
can you build from xcode itself?

**Comment by romainlouvet** [comment]
thanks for your reply

**Comment by yaphatak** [comment]
@romainlouvet : I think you logs look good @dnphung 
![wda](https://cloud.githubusercontent.com/assets/12143988/18771980/2dc4f412-80f8-11e6-9ad6-c6883dbf6a03.png)

**Comment by dnphung** [comment]
@yaphatak thank you! I missed to sign the WebDriverAgentRunner as well... now I can start my appium session. Nevertheless xpaths seems not to work anymore I guess...

**Comment by Hellengo** [comment]
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [WebDriverAgent] Device: Sep 26 16:03:04 Hellengo XCTRunner[877] <Notice>: Running tests...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[Xcode] 2016-09-26 16:03:21.509 xcodebuild[94532:3753183] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

[Xcode]
Testing failed:

[Xcode] 	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **


[Xcode] 2016-09-26 16:03:04.298597 XCTRunner[877:454673] Running tests...
2016-09-26 16:03:04.883925 XCTRunner[877:454673] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2016-09-26 16:03:04.884203 XCTRunner[877:454673] (dlopen_preflight(/var/containers/Bundle/Application/89540FB8-E2A6-4DF4-89AB-FBE139A6B8F1/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/KissXML.framework/KissXML
  Referenced from: /private/var/containers/Bundle/Application/89540FB8-E2A6-4DF4-89AB-FBE139A6B8F1/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/89540FB8-E2A6-4DF4-89AB-FBE139A6B8F1/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/KissXML.framework/KissXML: required code signature missing for '/private/var/containers/Bundle/Application/89540FB8-E2A6-4DF4-89AB-FBE139A6B8F1/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/KissXML.framework/KissXML'
)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (lib/webdriveragent.js:244:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
 Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (lib/webdriveragent.js:244:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
[XCUITest] Shutting down WebDriverAgent
[XCUITest] System log exited with code 'null'
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (lib/webdriveragent.js:244:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

**Comment by mikhailpractice** [comment]
@dnphung Were you able to launch the actual app on real device? My WebdriverAgent is launching but app is not running and no logs (its installing but not running). Did you resolve that part?
