### ISSUE TITLE
build-wda script is broken

### ISSUE THREAD

**Issue by jlipps** [appium/appium-xcuitest-driver#1505]
> appium driver run xcuitest build-wda

produces:

```
[STDERR] info WebDriverAgent Using WDA path: '/Users/jlipps/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'
[STDERR] info WebDriverAgent Using WDA agent: '/Users/jlipps/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[STDERR] Fatal TypeError: Cannot read properties of null (reading 'udid')
[STDERR]     at XcodeBuild.getCommand (/Users/jlipps/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/lib/xcodebuild.js:213:49)
[STDERR]     at XcodeBuild.createSubProcess (/Users/jlipps/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/lib/xcodebuild.js:252:30)
[STDERR]     at XcodeBuild.start (/Users/jlipps/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/lib/xcodebuild.js:316:34)
[STDERR]     at build (/Users/jlipps/.appium/node_modules/appium-xcuitest-driver/lib/build-wda.js:23:24)
✖ Encountered an error when running 'build-wda': Process ended with exitcode 2 (cmd: '/Users/jlipps/.nvm/versions/node/v16.13.1/bin/node ./build/lib/build-wda.js')
```

**Comment by mykola-mokhnach** [comment]
```js
  const deviceName = translateDeviceName(iosVersion, DEFAULT_SIM_NAME);
  const device = await getExistingSim({
    platformVersion: iosVersion,
    deviceName
  });
```

it looks like `getExistingSim` returned null since it was not able to find the device and since the script does not have a validation for it it did fail later during xcodebuild invocation. @KazuCocoa would you like to add the necessary validations (I also think it does not make much sense to hardcode the device name, but rather fetch it dynamically) or let me do it?

**Comment by mykola-mokhnach** [comment]
Closed as fixed
