### ISSUE TITLE
test note of iOS 17 with Xcode 15

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-xcuitest-driver#1752]
The list of tests we may need to check for ios 17 as this repository

- Need to check the faceID test app side
```
  4) XCUITestDriver - faceID -
       faceID enrollment functional tests applied to FaceID sample app
         should accept matching fingerprint if faceID is enrolled:
     Error: Element located by '-ios class chain:**/XCUIElementTypeStaticText[`label == "Face ID"`]' done not exist after 5000ms timeout
      at waitUntilExist (test/functional/basic/face-id-e2e-specs.js:64:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Context.<anonymous> (test/functional/basic/face-id-e2e-specs.js:96:9)

  5) XCUITestDriver - faceID -
       faceID enrollment functional tests applied to FaceID sample app
         should reject not matching fingerprint if faceID is enrolled:
     Error: Element located by '-ios class chain:**/XCUIElementTypeStaticText[`label == "Face ID"`]' done not exist after 5000ms timeout
      at waitUntilExist (test/functional/basic/face-id-e2e-specs.js:64:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Context.<anonymous> (test/functional/basic/face-id-e2e-specs.js:112:9)

  6) XCUITestDriver - faceID -
       faceID enrollment functional tests applied to FaceID sample app
         should enroll faceID and accept matching fingerprints then unenroll faceID and not be supported:
     Error: Element located by '-ios class chain:**/XCUIElementTypeStaticText[`label == "Face ID"`]' done not exist after 5000ms timeout
      at waitUntilExist (test/functional/basic/face-id-e2e-specs.js:64:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Context.<anonymous> (test/functional/basic/face-id-e2e-specs.js:137:9)
```

```
  8) XCUITestDriver - touchID -
       touchID enrollment functional tests applied to TouchId sample app
         "before each" hook for "should not support touchID if not enrolled":
     Error: Failed to create session.
An unknown server-side error occurred while processing the command. Original error: Could not create simulator with name 'appiumTest-C864A8C2-1155-41C1-83C4-8AAF6332483C-iPhone 8', device type id 'iPhone 8', with runtime ids 'com.apple.CoreSimulator.SimRuntime.iOS-17-0'
      at startWebDriverSession (file:///Users/kazu/GitHub/appium-xcuitest-driver/node_modules/webdriver/build/utils.js:68:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Function.newSession (file:///Users/kazu/GitHub/appium-xcuitest-driver/node_modules/webdriver/build/index.js:26:45)
      at async remote (file:///Users/kazu/GitHub/appium-xcuitest-driver/node_modules/webdriverio/build/index.js:48:22)
      at async initSession (test/functional/helpers/session.js:14:14)
      at async Context.<anonymous> (test/functional/basic/touch-id-e2e-specs.js:73:18)
```

**Comment by mwakizaka** [comment]
I'll try updating the tests if no problem

**Comment by Xiaotian0726** [comment]
> Real device set location should be via `com.apple.instruments.server.services.LocationSimulation` instead of `com.apple.dt.simulatelocation` over the remote server.

Is this rule for all iOS real devices or just iOS 17?

**Comment by KazuCocoa** [comment]
it is for iOS 17+. Please use https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-setsimulatedlocation . XCUITest driver calls it internally to set location for real devices for `location` command as well.

**Comment by Xiaotian0726** [comment]
> LocationSimulation

Thx, I got it.

**Comment by Xiaotian0726** [comment]
> it is for iOS 17+. Please use https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-setsimulatedlocation . XCUITest driver calls it internally to set location for real devices for `location` command as well.

Thx, I got it.

**Comment by eglitise** [comment]
@KazuCocoa I assume this issue can be closed?
