### ISSUE TITLE
Could not proxy command to remote server. Original error: Error: ETIMEDOUT

### ISSUE THREAD

**Issue by Hellengo** [appium/appium-xcuitest-driver#194]
appium:1.6.0-beta2
xcode:8.0
iOS device:10.0

Appium log:
[Xcode] 2016-09-29 19:26:05.462 xcodebuild[10661:4827623]  DTDeviceKit: Could not start house arrest service for app identifier com.apple.test.WebDriverAgentRunner-Runner [Error Domain=com.apple.dtdevicekit Code=-402653093 "Too many instances of this service are already running." UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x000000010be1f3cb DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x000000010be1fb09 DTDK_AMDErrorToNSError + 791
	2   DTDeviceKitBase                     0x000000010be312f5 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 100
	3   DTDeviceKitBase                     0x000000010be301d1 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_4 + 22
	4   DTDeviceKitBase                     0x000000010be22317 __DTDKExecuteInSession_block_invoke + 38
	5   DTDeviceKitBase                     0x000000010be21940 __DTDKExecuteWithConnection_block_invoke_2 + 477
	6   DTDeviceKitBase                     0x000000010be2173c __DTDKExecuteWithConnection_block_invoke + 107
	7   libdispatch.dylib                   0x00007fff87a1240b _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fff87a20a9a _dispatch_barrier_sync_f_slow + 856
	9   DVTFoundation                       0x0000000103438bef DVTDispatchBarrierSync + 206
	10  DVTFoundation                       0x000000010341559b -[DVTDispatchLock performLockedBlock:] + 116
	11  DTDeviceKitBase                     0x000000010be21646 DTDKExecuteWithConnection + 223
	12  DTDeviceKitBase                     0x000000010be222a1 DTDKExecuteInSession + 121
	13  DTDeviceKitBase                     0x000000010be30108 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 117
	14  DVTFoundation                       0x0000000103437f4b __DVTDispatchAsync_block_invoke + 827
	15  libdispatch.dylib                   0x00007fff87a1d93d _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x00007fff87a1240b _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x00007fff87a24bd7 _dispatch_async_redirect_invoke + 1733
	18  libdispatch.dylib                   0x00007fff87a1240b _dispatch_client_callout + 8
	19  libdispatch.dylib                   0x00007fff87a1629b _dispatch_root_queue_drain + 1890
	20  libdispatch.dylib                   0x00007fff87a15b00 _dispatch_worker_thread3 + 91
	21  libsystem_pthread.dylib             0x00007fff8c4a94de _pthread_wqthread + 1129
	22  libsystem_pthread.dylib             0x00007fff8c4a7341 start_wqthread + 13
), NSLocalizedRecoverySuggestion=Too many instances of this service are already running., NSLocalizedDescription=Too many instances of this service are already running.}]

[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[XCUITest] Detected that WebDriverAgent is running at url 'http://192.168.1.124:8100'
[XCUITest] WebDriverAgent started at url 'http://192.168.1.124:8100'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bu...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
......
......
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[XCUITest] ProxyRequestError: Could not proxy command to remote server. Original error: Error: ETIMEDOUT
    at JWProxy.proxy$ (lib/jsonwp-proxy/proxy.js:117:13)
    at tryCatch (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 { ProxyRequestError: Could not proxy command to remote server. Original error: Error: ETIMEDOUT
    at JWProxy.proxy$ (lib/jsonwp-proxy/proxy.js:117:13)
    at tryCatch (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
  jsonwp:
   { Error: ETIMEDOUT
       at Timeout._onTimeout (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/request/request.js:759:15)
       at tryOnTimeout (timers.js:232:11)
       at Timer.listOnTimeout (timers.js:202:5) code: 'ETIMEDOUT', connect: false } }
[XCUITest] Shutting down WebDriverAgent
[Xcode] ** BUILD INTERRUPTED **

[XCUITest] System log exited with code '0'
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: ETIMEDOUT
    at JWProxy.proxy$ (lib/jsonwp-proxy/proxy.js:117:13)
    at tryCatch (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

Session-WebDriverAgentRunner.log

19:31:28.117 xcodebuild[10962:4831865] Beginning test session WebDriverAgentRunner-5BE02F55-BFF9-484F-AB71-9FEEF3958CC1 at 2016-09-29 19:31:28.116 with Xcode 8A218a on target <DVTiOSDevice: 0x7fd0de697d60> {
		deviceSerialNumber:         F2LLC2E9FQ16
		identifier:                 0a7cccd713fb86055a2b326aa5f54ab683d1a706
		deviceClass:                iPhone
		deviceName:                 Hellengo
		deviceIdentifier:           0a7cccd713fb86055a2b326aa5f54ab683d1a706
		productVersion:             10.0.1
		buildVersion:               14A403
		deviceSoftwareVersion:      10.0.1 (14A403)
		deviceArchitecture:         armv7s
		deviceTotalCapacity:        28812226560
		deviceAvailableCapacity:    22478884864
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7fd0de463a30 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (10.0.1 (14A403))
19:31:28.117 xcodebuild[10962:4831865] 	/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
-project
/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
-scheme
WebDriverAgentRunner
-destination
id=0a7cccd713fb86055a2b326aa5f54ab683d1a706
build
test
19:31:28.117 xcodebuild[10962:4831865] Launching with Xcode.IDEFoundation.Launcher.PosixSpawn
19:31:28.120 xcodebuild[10962:4831865] Initializing test infrastructure.
19:31:28.807 xcodebuild[10962:4831872] Creating the test bundle connection.
19:31:28.808 xcodebuild[10962:4831872] Listening for proxy connection request from the test bundle (all platforms)
19:31:28.808 xcodebuild[10962:4831872] Resuming the connection.
19:31:28.808 xcodebuild[10962:4831872] Test connection requires daemon assistance.
19:31:28.809 xcodebuild[10962:4831865] Starting test session with ID <__NSConcreteUUID 0x7fd0de6ce360> 5BE02F55-BFF9-484F-AB71-9FEEF3958CC1
19:31:28.809 xcodebuild[10962:4831865] Checking test manager availability..., will wait up to 120s
19:31:28.914 xcodebuild[10962:4831870] testmanagerd handled session request.
19:31:28.915 xcodebuild[10962:4831865] Waiting for test process to launch.
19:31:34.017 xcodebuild[10962:4831865] Launch session started, setting a disallow-finish-token on the run operation.
19:31:34.164 xcodebuild[10962:4832319] app uninstall set - {(
)}
19:31:34.164 xcodebuild[10962:4832319] app install set - {(
    <DVTFilePath:0x7fd0deade1f0:'/Users/Hellengo/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/build/Debug-iphoneos/WebDriverAgentRunner-Runner.app'>
)}
19:31:37.761 xcodebuild[10962:4831880] remoteExecutable setInstalledPath:/private/var/containers/Bundle/Application/DD4431C9-2DCD-49D3-A129-94A18CF2226F/WebDriverAgentRunner-Runner.app

19:31:37.762 xcodebuild[10962:4831880] Updated test configuration at /var/folders/br/9sgfr0m94g56qmxgp61pf33r0000gn/T/com.apple.dt.XCTest/5BE02F55-BFF9-484F-AB71-9FEEF3958CC1/remote-container/tmp/WebDriverAgentRunner-5BE02F55-BFF9-484F-AB71-9FEEF3958CC1.xctestconfiguration with device paths: <XCTestConfiguration: 0x7fd0de6edaf0>
	                  testBundleURL:file:///private/var/containers/Bundle/Application/DD4431C9-2DCD-49D3-A129-94A18CF2226F/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
	         testBundleRelativePath:(null)
	              productModuleName:WebDriverAgentRunner
	                    testsToSkip:(null)
	                     testsToRun:(null)
	             reportResultsToIDE:YES
	              sessionIdentifier:<__NSConcreteUUID 0x7fd0de6ce360> 5BE02F55-BFF9-484F-AB71-9FEEF3958CC1
	     pathToXcodeReportingSocket:(null)
	      disablePerformanceMetrics:no
	treatMissingBaselinesAsFailures:no
	                baselineFileURL:(null)
	       baselineFileRelativePath:(null)
	          targetApplicationPath:(null)
	      targetApplicationBundleID:(null)
	               reportActivities:YES
	       testsMustRunOnMainThread:YES
	         initializeForUITesting:YES
	 aggregateStatisticsBeforeCrash:{
    XCSuiteRecordsKey =     {
    };
}

19:31:39.613 xcodebuild[10962:4831865] Adding console adaptor <IDEConsoleAdaptor: 0x7fd0ded1d630 'target'> for test session 5BE02F55-BFF9-484F-AB71-9FEEF3958CC1.
19:31:40.728 xcodebuild[10962:4831865] Test process runnable PID is 1037.

**Comment by Hellengo** [comment]
Reboot my phone, it works.
