### ISSUE TITLE
Wrong button being clicked

### ISSUE THREAD

**Issue by joshrlesch** [appium/appium-xcuitest-driver#209]
ok this is a difficult one, but we are seeing the wrong buttons being clicked. All of the logs look fine with no errors, its just that it literally clicks the wrong button in the app. So its hard to give logs and debug info.

I saw this after upgrading the appium-xcuitest-driver by doing `npm uninstall -g appium && npm install -g appium@beta`. This picked up v2.0.23. Nothing has changed in our app and I know this used to work. So I started to downgrade the driver until it started working again which was v2.0.19. So something in v2.0.20 is causing this issue. :/

If you want any info for debugging this, I will give it to you.

**Comment by imurchie** [comment]
Since it seems unlikely that we will be able to reproduce this, can you do a little investigating? I'm willing to bet, given the changes that have happened, that this is from the update of the underlying WebDriverAgent. To see if this is true, can you get the latest from `appium-xcuitest-driver` (version `2.0.23`), then get a copy of the WebDriverAgent and get it to the previous commit:

```
// somewhere temporary
git clone https://github.com/facebook/WebDriverAgent.git
cd WebDriverAgent
git checkout e05cce2d6f1e43ea52ac4a7a9ab0dd22650fcb8e
```

You should see some output ending with `HEAD is now at e05cce2... Add health check enpoint`.

Now get the full path to that WebDriverAgent directory, and pass it into your test in _both_ the `agentPath` and `bootstrapPath` desired capabilities (these might cause a log line to be generated saying they are not recognized, but don't worry about that).

This should make the system use the different WDA installation, which is in the state the driver version `2.0.20` was in.

Phew!

Anyway, hopefully that will work, and we can start figuring out what changed in the WDA system that would cause this.

**Comment by joshrlesch** [comment]
So looks like when using those two caps, it passing in the wrong value for `-project` in the xcodebuild command
```
[Appium] Welcome to Appium v1.6.0-beta3
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"launchTimeout":300,"termTimeout":300,"platformVersion":"10.0","deviceName":"iPhone 6","newCommandTimeout":1800,"agentPath":"/Users/josh.lesch/Documents/Github/Open_Source_Repos/WebDriverAgent","applicationName":"iPhone 6","bootstrapPath":"/Users/josh.lesch/Documents/Github/Open_Source_Repos/WebDriverAgent","fullReset":true,"orientation":"PORTRAIT","automationName":"xcuitest","app":"/Users/josh.lesch/Library/Developer/Xcode/DerivedData/Hudl-auptglmoilgtftbgkoxuuntozxoc/Build/Products/Debug-iphonesimulator/Hudl.app","version":"10.0","platformName":"iOS","noReset":false}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"launchTimeout":300,"term...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   launchTimeout: 300
[Appium]   termTimeout: 300
[Appium]   platformVersion: '10.0'
[Appium]   deviceName: 'iPhone 6'
[Appium]   newCommandTimeout: 1800
[Appium]   agentPath: '/Users/josh.lesch/Documents/Github/Open_Source_Repos/WebDriverAgent'
[Appium]   applicationName: 'iPhone 6'
[Appium]   bootstrapPath: '/Users/josh.lesch/Documents/Github/Open_Source_Repos/WebDriverAgent'
[Appium]   fullReset: true
[Appium]   orientation: 'PORTRAIT'
[Appium]   automationName: 'xcuitest'
[Appium]   app: '/Users/josh.lesch/Library/Developer/Xcode/DerivedData/Hudl-auptglmoilgtftbgkoxuuntozxoc/Build/Products/Debug-iphonesimulator/Hudl.app'
[Appium]   version: '10.0'
[Appium]   platformName: 'iOS'
[Appium]   noReset: false
[debug] [XCUITest] XCUITestDriver version: 2.0.23
[BaseDriver] The following capabilities were provided, but are not recognized by appium: termTimeout, agentPath, applicationName, bootstrapPath, version.
[BaseDriver] Session created with session id: 087fc1d2-e810-44c9-afc6-656f82c423aa
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[iOSSim] Constructing iOS simulator for Xcode version 8.0 with udid '288AA950-08C2-4F8C-9228-05B64A501ED8'
[debug] [iOSSim] Killing any simulator daemons for 288AA950-08C2-4F8C-9228-05B64A501ED8
[iOSSim] Cleaning simulator 288AA950-08C2-4F8C-9228-05B64A501ED8
[debug] [iOSSim] Killing all iOS Simulators
[XCUITest] Determining device to run tests on: udid: '288AA950-08C2-4F8C-9228-05B64A501ED8', real device: false
[BaseDriver] Using local app '/Users/josh.lesch/Library/Developer/Xcode/DerivedData/Hudl-auptglmoilgtftbgkoxuuntozxoc/Build/Products/Debug-iphonesimulator/Hudl.app'
[debug] [XCUITest] Checking whether app is actually present
[debug] [ios-app-utils] Getting bundle ID from app
[debug] [iOSLog] Starting iOS 10.0 simulator log capture
[debug] [iOSLog] System log path: /Users/josh.lesch/Library/Logs/CoreSimulator/288AA950-08C2-4F8C-9228-05B64A501ED8/system.log
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid '288AA950-08C2-4F8C-9228-05B64A501ED8' not booted. Booting up now
[debug] [iOSSim] Killing all iOS Simulators
[iOSSim] Starting simulator with command: open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 288AA950-08C2-4F8C-9228-05B64A501ED8
[iOSSim] Tailing simulator logs until we encounter the string "SMS Plugin initialized"
[iOSSim] We will time out after 60000ms
[debug] [iOSSim] Waiting an extra 10000ms for the simulator to really finish booting
[debug] [iOSSim] Done waiting extra time for simulator
[iOSSim] Simulator booted in 27745ms
[XCUITest] Custom agent path specified: /Users/josh.lesch/Documents/Github/Open_Source_Repos/WebDriverAgent
[XCUITest] Custom bootstrap path specified: /Users/josh.lesch/Documents/Github/Open_Source_Repos/WebDriverAgent
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Beginning test with command 'xcodebuild -project /Users/josh.lesch/Documents/Github/Open_Source_Repos/WebDriverAgent -scheme WebDriverAgentRunner -destination id=288AA950-08C2-4F8C-9228-05B64A501ED8 build test' in directory '/Users/josh.lesch/Documents/Github/Open_Source_Repos/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[XCUITest] xcodebuild exited with code '66' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 66
    at SubProcess.<anonymous> (lib/webdriveragent.js:261:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
 Error: xcodebuild failed with code 66
    at SubProcess.<anonymous> (lib/webdriveragent.js:261:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'command' of undefined
    at XCUITestDriver.callee$0$0$ (lib/commands/proxy-helper.js:13:35)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.callee$0$0 [as proxyCommand] (lib/commands/proxy-helper.js:13:10)
    at XCUITestDriver.stop$ (lib/driver.js:266:18)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.stop (lib/driver.js:263:16)
    at XCUITestDriver.deleteSession$ (lib/driver.js:254:16)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.deleteSession (lib/driver.js:253:23)
    at XCUITestDriver.createSession$ (lib/driver.js:143:18)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 45101 ms - 180
```

**Comment by imurchie** [comment]
Oh shoot! I mislead you. The `agentPath` cap should be the directory, plus `/WebDriverAgent.xcodeproj`. :( It needs to point to the project itself.

**Comment by joshrlesch** [comment]
no worries, I figured that out :)

But I tried that wda commit and it still clicked the wrong button, so I have been going down the list of commits but they all don't seem to work, I made it to `b2e1c07d1028b696708b64b130292770b72e8052`

**Comment by joshrlesch** [comment]
@imurchie well I jumped the guy, WDA commit `eb8514512703f54dda0a9953a3be6755f572a7b8` worked, but `b2e1c07d1028b696708b64b130292770b72e8052` didn't.

**Comment by imurchie** [comment]
Alrighty. Thanks for the investigation.

One more thing to try. Can you do the same, but for my fork, in which I've reverted the commit after the one you identified (which does have to do with clicking, so that checks out).

```
// somewhere temporary
git clone https://github.com/imurchie/WebDriverAgent.git
```

And do the same with the directory/xcode project file.

Thanks!

**Comment by joshrlesch** [comment]
Ok so cloned your fork, updated the `agentPath` and `bootstrapPath` to point to it, and the test passes.

**Comment by imurchie** [comment]
Alrighty. I will open an issue on WDA and link to here. Thanks for all the work in getting to the bottom of this.

**Comment by joshrlesch** [comment]
No worries man. Thanks for the fast turn around.

**Comment by imurchie** [comment]
@joshrlesch Can you provide more detail about the error. How is the view laid out? It seems like the upstream maintainer doesn't feel like fixing it unless I can produce a reproduction case.

**Comment by joshrlesch** [comment]
yeah I saw that :( So the view that it happens on are very complex ones that load a lot of elements into memory but not all are visible at a give time. 

There really is no error, but trying to figure out how to get more info on why its clicking the wrong button. 

I'll get you the DOM of the page state and the appium logs of the command that is being sent, maybe something is off that I'm missing.

**Comment by joshrlesch** [comment]
@imurchie https://gist.github.com/joshrlesch/d7651d49b3d9e28e234f1fe0c36ebb94

**Comment by pavanbachu0604** [comment]
@joshrlesch : were you able to fix it ? I am facing the same issue in appium 1.6 (final version). It is able to recognise the xpath but it is not clicking

**Comment by joshrlesch** [comment]
I have not, but @imurchie I think it might have something to do with being in landscape mode. Whenever it clicks on the wrong button, our app is forcing landscape mode. Like when entering a video player, the app locks it in landscape.

@pavanbachu0604 are you in landscape when the wrong element is being clicked?

**Comment by pavanbachu0604** [comment]
Yeah its not clicking on right element when its in landscape mode , I need to test it in portrait mode

**Comment by pavanbachu0604** [comment]
@joshrlesch Any updates ? I am struck at that same point and worst thing is that app I am testing on is completely in landscape mode

**Comment by joshrlesch** [comment]
Believe it is being looked at by WDA

**Comment by maesiva** [comment]
My app too works only in Landscape mode and am blocked due to this issue. Eager to see a fix soon!

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7428](https://github.com/appium/appium/issues/7428) via [**ZenHub**](https://www.zenhub.com/)
