### ISSUE TITLE
throw error like:  unrecognized selector sent to instance 0x100f52320

### ISSUE THREAD

**Issue by SayWeeeXuZhongyuan** [appium/appium-xcuitest-driver#2297]
**Warning:**

logs as below: 
Proxying [POST /element] to [POST http://127.0.0.1:8100/session/C0FBEE10-13E3-4AD5-BCF7-59F2E4A74987/element] with body: {"using":"xpath","value":"//XCUIElementTypeTextField[@value='What are you looking for?']"}
[XCUITestDriver@3268 (07a35492)] Got response with status 200: {"value":{"ELEMENT":"38000000-0000-0000-441B-000000000000","element-6066-11e4-a52e-4f735466cecf":"38000000-0000-0000-441B-000000000000"},"sessionId":"C0FBEE10-13E3-4AD5-BCF7-59F2E4A74987"}
[XCUITestDriver@3268 (07a35492)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"38000000-0000-0000-441B-000000000000","ELEMENT":"38000000-0000-0000-441B-000000000000"}
[HTTP] <-- POST /session/07a35492-e6fe-428a-9549-379293b5fd8e/element 200 5002 ms - 137
[HTTP] 
[HTTP] --> POST /session/07a35492-e6fe-428a-9549-379293b5fd8e/element/38000000-0000-0000-441B-000000000000/clear
[HTTP] {}
[XCUITestDriver@3268 (07a35492)] Calling AppiumDriver.clear() with args: ["38000000-0000-0000-441B-000000000000","07a35492-e6fe-428a-9549-379293b5fd8e"]
[XCUITestDriver@3268 (07a35492)] Executing command 'clear'
[XCUITestDriver@3268 (07a35492)] Matched '/element/38000000-0000-0000-441B-000000000000/clear' to command name 'clear'
[XCUITestDriver@3268 (07a35492)] Proxying [POST /element/38000000-0000-0000-441B-000000000000/clear] to [POST http://127.0.0.1:8100/session/C0FBEE10-13E3-4AD5-BCF7-59F2E4A74987/element/38000000-0000-0000-441B-000000000000/clear] with no body
[XCUITestDriver@3268 (07a35492)] Got response with status 500: {"value":{"error":"unknown error","message":"-[XCElementSnapshot systemAutomationProperties]: unrecognized selector sent to instance 0x100f52320","traceback":"(\n\t0   CoreFoundation                      0x0000000180e9bd20 48CD0A80-7A92-34EB-B140-8C475D135808 + 601376\n\t1   libobjc.A.dylib                     0x000000019868cee4 objc_exception_throw + 56\n\t2   CoreFoundation                      0x0000000180f6c750 48CD0A80-7A92-34EB-B140-8C475D135808 + 1455952\n\t3   CoreFoundation                      0x0000000180e3560c 48CD0A80-7A92-34EB-B140-8C475D135808 + 181772\n\t4   CoreFoundation                      0x0000000180e3481c _CF_forwarding_prep_0 + 92\n\t5   XCUIAutomation                      0x0000000100e067dc __125+[XCUIElementBaseEventTarget _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:]_block_invoke.37 + 212\n\t6   XCTestCore                          0x0000000100c60cf4 +[XCTFuture futureWithDescription:block:] + 108\n\t7   XCUIAutomation            ...
[W3C] Matched W3C error code 'unknown error' to UnknownError
[XCUITestDriver@3268 (07a35492)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[XCElementSnapshot systemAutomationProperties]: unrecognized selector sent to instance 0x100f52320
[XCUITestDriver@3268 (07a35492)]     at errorFromW3CJsonCode (/Users/zhongyuan.xu/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1085:25)
[XCUITestDriver@3268 (07a35492)]     at ProxyRequestError.getActualError (/Users/zhongyuan.xu/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:954:14)
[XCUITestDriver@3268 (07a35492)]     at JWProxy.command (/Users/zhongyuan.xu/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:353:19)
[XCUITestDriver@3268 (07a35492)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[XCUITestDriver@3268 (07a35492)]     at XCUITestDriver.proxyCommand (/Users/zhongyuan.xu/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:109:35)
[XCUITestDriver@3268 (07a35492)]     at XCUITestDriver.clear (/Users/zhongyuan.xu/.appium/node_modules/appium-xcuitest-driver/lib/commands/element.js:291:5)
[HTTP] <-- POST /session/07a35492-e6fe-428a-9549-379293b5fd8e/element/38000000-0000-0000-441B-000000000000/clear 500 829 ms - 1267

**Comment by SayWeeeXuZhongyuan** [comment]
![image](https://github.com/appium/appium-xcuitest-driver/assets/150754251/00dd1631-559b-441b-a919-044c2204be3b)

**Comment by KazuCocoa** [comment]
Could you share the full appium log to check other information?
