### ISSUE TITLE
[XCUITest] Error: Could not find app at <package name of the app> even though the app is installed on the phone

### ISSUE THREAD

**Issue by harjotcheema** [appium/appium-xcuitest-driver#237]
We are getting the below error when trying to run XCUITests:

[debug] [XCUITest] XCUITestDriver version: 2.0.26
[BaseDriver] Session created with session id: 01522e1d-132a-4b86-beff-2214b47ef1a1
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[debug] [XCUITest] Available devices: **<udid of the device>**
[debug] [XCUITest] Creating iDevice object with udid **(udid of the device)**
[XCUITest] Determining device to run tests on: udid: '**(udid of the device)**', real device: true
[debug] [XCUITest] Checking whether app is actually present
[XCUITest] Error: Could not find app at **(package name of the app)**
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at XCUITestDriver.checkAppPresent$ (lib/driver.js:314:11)
    at tryCatch (/salt/homebrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/salt/homebrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/salt/homebrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/salt/homebrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/salt/homebrew/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /salt/homebrew/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/salt/homebrew/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 **[Error: Could not find app at (package name of the app)]**

Environment:
Xcode version - Xcode 8.0
OSX Version - El Capitan (10.11.5)
Appium Version - 1.6.0
Device - iPhone 6 (iOS 10.0)

**Note: The app is installed on the phone**

Can you please help to resolve this issue.

**Comment by imurchie** [comment]
Are you specifying an `app` or a `bundleId`?

**Comment by harjotcheema** [comment]
Appium is already detecting the app:

[Appium] Welcome to Appium v1.6.0
[Appium] Non-default server args:
[Appium]   port: 47040
[Appium]   app: '**(package name of the app)**'
[Appium]   udid: '**(udid of the device)**'
[Appium] Deprecated server args:
[Appium]   --app => --default-capabilities '{"app":"**(package name of the app)**"}'
[Appium]   -U,--udid => --default-capabilities '{"udid":"**(udid of the device)**"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   app: '**(package name of the app)**'
[Appium]   udid: '**(udid of the device)**'
[Appium] Appium REST http interface listener started on 0.0.0.0:47040
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 7 ms - 40 


[MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"iPhone 6","...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   deviceName: 'iPhone 6'
[Appium]   autoAcceptAlerts: true
[Appium]   automationName: 'XCUITest'
[Appium]   seleniumAddress: '**(selenium address)**'
[Appium]   browserName: ''
[Appium]   xcodeConfigFile: 'config.xcconfig'
[Appium]   device: 'iphone'
[Appium]   platformName: 'iOS'
[Appium]   appurify_videocapture: 'True'
[Appium]   platformVersion: '10.0'
[Appium]   app: '**(package name of the app)**'
[Appium]   udid: '**(udid of the device)**'
[debug] [XCUITest] XCUITestDriver version: 2.0.26

**Comment by imurchie** [comment]
Yes. But it thinks the app is a file on the file system. Try specifying it
as a bundleId.

**Comment by harjotcheema** [comment]
It failed with the same error even after specifying the bundleId. Please see below:

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"iPhone 6","...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   deviceName: 'iPhone 6'
[Appium]   autoAcceptAlerts: true
[Appium]   automationName: 'XCUITest'
[Appium]   seleniumAddress: '**(Selenium address)**'
[Appium]   browserName: ''
[Appium]   xcodeConfigFile: 'config.xcconfig'
[Appium]   device: 'iphone'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.0'
[Appium]   bundleId: '**(package name of the app)**'
[Appium]   app: '**(package name of the app)**'
[Appium]   udid: '**(udid of the device)**'
[debug] [XCUITest] XCUITestDriver version: 2.0.26
[BaseDriver] Session created with session id: 512df4b5-689f-484a-b12f-571ffedaf0ce
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[debug] [XCUITest] Available devices: **(udid of the device)**
[debug] [XCUITest] Creating iDevice object with udid **(udid of the device)**
[XCUITest] Determining device to run tests on: udid: '**(udid of the device)**', real device: true
[debug] [XCUITest] App is an iOS bundle, will attempt to run as pre-existing
[debug] [XCUITest] Checking whether app is actually present
[XCUITest] Error: Could not find app at **(package name of the app)**
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at XCUITestDriver.checkAppPresent$ (lib/driver.js:314:11)
    at tryCatch (/salt/homebrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/salt/homebrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/salt/homebrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/salt/homebrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/salt/homebrew/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /salt/homebrew/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/salt/homebrew/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 [Error: Could not find app at **(package name of the app)**]

**Comment by imurchie** [comment]
Do _not_ specify an `app`.

**Comment by imurchie** [comment]
Hmm. Looks like that won't work, either. Fixing.

**Comment by harjotcheema** [comment]
Thank you.
