### ISSUE TITLE
Could not start session

### ISSUE THREAD

**Issue by pppppino** [appium/appium-xcuitest-driver#2401]
appium version: **2.5.4**
xcuitest version: **7.16.2**

error: 
E       selenium.common.exceptions.SessionNotCreatedException: Message: Could not start a new session. Could not start a new session. Error while creating session with the service http://******:4725/. Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: **Could not find a driver for automationName 'xcuitest' and platformName 'IOS'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Could not find installed driver to support given caps)** 

but I do installed XCUITest driver: 
![image](https://github.com/appium/appium-xcuitest-driver/assets/129264630/74ca6c29-b03b-436c-9974-29ee1c5e5586)

**Comment by pppppino** [comment]
appium & driver: **all latest version**

I have uninstall and reinstall appium, above problem can not reproduce, but I got a new problem:

**Could not determine Xcode version: undefined**

@KazuCocoa , Hi, Could you please help me to check this problem.

```
[38;5;48m[BaseDriver][0m Number capability passed in as string. Functionality may be compromised.
[38;5;32m[XCUITestDriver@0b51][0m Capability 'wdaLocalPort' changed from string ('8100') to integer (8100). This may cause unexpected behavior
[38;5;32m[XCUITestDriver@0b51][0m The following provided capabilities were not recognized by this driver:
[38;5;32m[XCUITestDriver@0b51][0m   resetKeyboard
[38;5;32m[XCUITestDriver@0b51][0m   unicodeKeyboard
[38;5;32m[XCUITestDriver@0b51 (db4f01c8)][0m Session created with session id: db4f01c8-aea9-4750-819a-32ef49b3781f
[38;5;64m[XCUITest][0m Current user: 'admin'
[38;5;32m[XCUITestDriver@0b51 (db4f01c8)][0m Available real devices: 00008120-001E519036A1A01E, 365600ebfdab09be15315bf858fd8871ce546ac1, c2faf99cb910025649c7dbf0f95bb778f46c805f
[38;5;32m[XCUITestDriver@0b51 (db4f01c8)][0m Creating iDevice object with udid '00008120-001E519036A1A01E'
[38;5;32m[XCUITestDriver@0b51 (db4f01c8)][0m Determining device to run tests on: udid: '00008120-001E519036A1A01E', real device: true
[38;5;32m[XCUITestDriver@0b51 (db4f01c8)][0m Normalized platformVersion capability value '15.6.1' to '15.6'
[38;5;80m[Xcode][0m '/Library/Developer/CommandLineTools' is not a valid Xcode path. Consider running:
[38;5;80m[Xcode][0m     sudo xcode-select -s "/Applications/Xcode.app/Contents/Developer"
[38;5;80m[Xcode][0m to address this issue.
[38;5;64m[XCUITest][0m '/Library/Developer/CommandLineTools' is not a valid Xcode path. Consider running:
[38;5;64m[XCUITest][0m     sudo xcode-select -s "/Applications/Xcode.app/Contents/Developer"
[38;5;64m[XCUITest][0m to address this issue.
[38;5;32m[XCUITestDriver@0b51 (db4f01c8)][0m {}
[38;5;96m[DevCon Factory][0m Releasing connections for 00008120-001E519036A1A01E device on any port number
[38;5;96m[DevCon Factory][0m No cached connections have been found
[38;5;16m[AppiumDriver@f51d][0m Event 'newSessionStarted' logged at 1717118702014 (09:25:02 GMT+0800 (China Standard Time))
[38;5;16m[AppiumDriver@f51d][0m Encountered internal error running command: Error: Could not determine Xcode version: undefined
[38;5;16m[AppiumDriver@f51d][0m     at getAndCheckXcodeVersion (/Users/admin/.appium/node_modules/appium-xcuitest-driver/lib/utils.js:35:11)
[38;5;16m[AppiumDriver@f51d][0m     at XCUITestDriver.start (/Users/admin/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:527:27)
[38;5;16m[AppiumDriver@f51d][0m     at XCUITestDriver.createSession (/Users/admin/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:413:7)
[38;5;16m[AppiumDriver@f51d][0m     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:717:35)
[38;5;0m[HTTP][0m [37m<-- POST /session [39m[31m500[39m [90m167 ms - 588[39m
[38;5;0m[HTTP][0m [90m[39m
```

**Comment by KazuCocoa** [comment]
Did you fix the issue addressed below?
```
�[38;5;32m[XCUITestDriver@0b51 (db4f01c8)]�[0m Normalized platformVersion capability value '15.6.1' to '15.6'
�[38;5;80m[Xcode]�[0m '/Library/Developer/CommandLineTools' is not a valid Xcode path. Consider running:
�[38;5;80m[Xcode]�[0m     sudo xcode-select -s "/Applications/Xcode.app/Contents/Developer"
�[38;5;80m[Xcode]�[0m to address this issue.
�[38;5;64m[XCUITest]�[0m '/Library/Developer/CommandLineTools' is not a valid Xcode path. Consider running:
�[38;5;64m[XCUITest]�[0m     sudo xcode-select -s "/Applications/Xcode.app/Contents/Developer"
�[38;5;64m[XCUITest]�[0m to address this issue.
�[38;5;32m[XCUITestDriver@0b51 (db4f01c8)]�[0m {}
```

**Comment by pppppino** [comment]
@KazuCocoa  thanks a lot, it's this issue block me, now driver is working
