### ISSUE TITLE
error when removing app

### ISSUE THREAD

**Issue by joshrlesch** [appium/appium-xcuitest-driver#245]
I'm trying to remove the app by the bundle id, but feel like I might be doing something wrong.

I want control over closing and removing the app, so calling
```
self.driver.close_app()
self.driver.remove_app("com.hudl.modi")
```
the `remove_app` method errors out
```
[HTTP] --> POST /wd/hub/session/8240750d-87f4-4be7-8338-d559fe10cdea/appium/device/remove_app {"sessionId":"8240750d-87f4-4be7-8338-d559fe10cdea","appId":"com.hudl.modi"}
[MJSONWP] Calling AppiumDriver.removeApp() with args: ["com.hudl.modi","8240750d-...
[debug] [XCUITest] Executing command 'removeApp'
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'removeApp' of null
    at XCUITestDriver.callee$0$0$ (lib/commands/general.js:88:27)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.callee$0$0 [as removeApp] (lib/commands/general.js:84:46)
    at lib/basedriver/driver.js:174:24
    at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
[HTTP] <-- POST /wd/hub/session/8240750d-87f4-4be7-8338-d559fe10cdea/appium/device/remove_app 500
```

Unless there is a combo of capabilities to remove the app but leave the simulator open and running?

**Comment by imurchie** [comment]
Hmm. Yes, `closeApp` gets rid of the device, and `removeApp` tries to use it.

What happens if you run them the other way around?

**Comment by joshrlesch** [comment]
I just removed the `close_app()`, and it seems to remove the app but 
leaves the simulator with a black screen. 
```
[HTTP] --> POST /wd/hub/session/2f60043c-3bab-4f89-920f-4b468f5c94c0/appium/device/remove_app {"sessionId":"2f60043c-3bab-4f89-920f-4b468f5c94c0","appId":"com.hudl.modi"}
[MJSONWP] Calling AppiumDriver.removeApp() with args: ["com.hudl.modi","2f60043c-...
[debug] [XCUITest] Executing command 'removeApp'
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [WebDriverAgent] Sim: Oct 17 12:57:02 jlesch16m CoreSimulatorBridge[8828]: Pasteboard change listener callback port <NSMachPort: 0x7fe7c460f3a0> registered
[debug] [WebDriverAgent] Sim: Oct 17 12:57:02 jlesch16m CoreSimulatorBridge[8828]: Pasteboard change listener callback port <NSMachPort: 0x7fe7c460f3a0> registered
[MJSONWP] Responding to client with driver.removeApp() result: null
[HTTP] <-- POST /wd/hub/session/2f60043c-3bab-4f89-920f-4b468f5c94c0/appium/device/remove_app 200 102 ms - 76
```
![screen shot 2016-10-17 at 1 01 26 pm](https://cloud.githubusercontent.com/assets/8480230/19449210/3bef83ec-946a-11e6-8e5d-1212ecbdbd8c.png)

**Comment by joshrlesch** [comment]
This seems like a different issue and doesn't affect tests. Closing
