### ISSUE TITLE
when I do any operation it gives an error like click swipe.

### ISSUE THREAD

**Issue by hakantektas** [appium/appium-xcuitest-driver#2477]
iOS 18 ,
macOS : Sonoma
XCode 15.1 and XCode 16,
appium version 2.11.5,
xcuitest@7.26.4

when i do any operation it gives this error like click swipe 

 Calling AppiumDriver.getPageSource() with args: ["f6aec358-f69d-4c50-b4fb-10b998ff70da"]
2024-10-07 09:33:58:608 - [f6aec358][XCUITestDriver@ca28] Executing command 'getPageSource'
2024-10-07 09:33:58:609 - [f6aec358][XCUITestDriver@ca28] Matched '/source?format=xml&scope=AppiumAUT' to command name 'getPageSource'
2024-10-07 09:33:58:610 - [f6aec358][XCUITestDriver@ca28] Proxying [GET /source?format=xml&scope=AppiumAUT] to [GET http://127.0.0.1:8100/session/367F2B39-127C-44B9-B24A-18680849A764/source?format=xml&scope=AppiumAUT] with no body
2024-10-07 09:33:58:622 - [f6aec358][XCUITestDriver@ca28] Got response with status 500: {"value":{"error":"unknown error","message":"-[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]: unrecognized selector sent to instance 0x3027a5d00","traceback":"(\n\t0   CoreFoundation                      0x000000018be89098 47427277-EE15-3C17-AD68-6886B0380B5E + 540824\n\t1   libobjc.A.dylib                     0x000000018918b2e4 objc_exception_throw + 88\n\t2   CoreFoundation                      0x000000018bf8f7c8 47427277-EE15-3C17-AD68-6886B0380B5E + 1615816\n\t3   CoreFoundation                      0x000000018be26888 47427277-EE15-3C17-AD68-6886B0380B5E + 137352\n\t4   CoreFoundation                      0x000000018be261b0 _CF_forwarding_prep_0 + 96\n\t5   WebDriverAgentLib                   0x0000000105d720d8 -[XCUIElement(FBUtilities) fb_waitUntilStableWithTimeout:] + 308\n\t6   WebDriverAgentLib                   0x0000000105d28ac8 +[FBXPath writeXmlWithRootElement:indexPath:elementStore:includedAttributes:writer:] + 632\n\t7   WebDriverAgentLib                   0x0000000105d28...
2024-10-07 09:33:58:622 - [f6aec358][W3C] Matched W3C error code 'unknown error' to UnknownError
2024-10-07 09:33:58:623 - [f6aec358][XCUITestDriver@ca28] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]: unrecognized selector sent to instance 0x3027a5d00
    at errorFromW3CJsonCode (/Users/mobven/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)
    at ProxyRequestError.getActualError (/Users/mobven/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)
    at JWProxy.command (/Users/mobven/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:348:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at XCUITestDriver.proxyCommand (/Users/mobven/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)
    at XCUITestDriver.mobileGetSource (/Users/mobven/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:50:35)
    at XCUITestDriver.getPageSource (/Users/mobven/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:25:9)
2024-10-07 09:33:58:624 - [f6aec358][HTTP] <-- GET /wd/hub/session/f6aec358-f69d-4c50-b4fb-10b998ff70da/source 500 16 ms - 1411

**Comment by KazuCocoa** [comment]
Duplication of https://github.com/appium/appium/issues/20239#issuecomment-2277352021 . Please make sure WDA removal and cache are cleaned on your xcodebuild environment https://appium.github.io/appium-xcuitest-driver/latest/guides/troubleshooting/#caching-issues-during-build
