### ISSUE TITLE
[enhancement] longpress method not inplemented 

### ISSUE THREAD

**Issue by dengwei729** [appium/appium-xcuitest-driver#256]
try to longpress on a special point:
code:
`driver.tap([(200, 300)], 200)`

message:

```
Traceback (most recent call last):
  File "/Users/dengwei/Documents/django_test/mysite/test/test_appium.py", line 18, in <module>
    driver.tap([(200, 300)], 200)
  File "/Library/Python/2.7/site-packages/appium/webdriver/webdriver.py", line 203, in tap
    action.perform()
  File "/Library/Python/2.7/site-packages/appium/webdriver/common/touch_action.py", line 94, in perform
    self._driver.execute(Command.TOUCH_ACTION, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
selenium.common.exceptions.WebDriverException: Message: Support for gestures other than Tap is not yet implemented. Please contact an Appium dev
```

**selenium.common.exceptions.WebDriverException: Message: Support for gestures other than Tap is not yet implemented. Please contact an Appium dev**

**Comment by imurchie** [comment]
Can you provide the server logs for the command (the full logs, if possible. Otherwise at least from the HTTP request for this command to the HTTP response). Long press is implemented, but this command might be triggering something else.

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7434](https://github.com/appium/appium/issues/7434) via [**ZenHub**](https://www.zenhub.com/)
