### ISSUE TITLE
Driver does not accept ZIP files in appPath capabilities

### ISSUE THREAD

**Issue by midopa** [appium/appium-xcuitest-driver#37]
This is a feature that is supported in the standard iOS driver, but when I pass a ZIP file, the driver fails:

```
info HTTP --> POST /wd/hub/session {"desiredCapabilities":{"app":"URL_TO_ZIP_FILE","showIOSLog":true,"sendKeyStrategy":"grouped","newCommandTimeout":10000,"platformVersion":"9.3","bundleId":"","platformName":"iOS","udid":null,"deviceName":"iPhone 6"}}
info MJSONWP Calling WebDriverAgentDriver.createSession() with args: [{"app":"URL_TO_ZIP_FILE","showIOSLog":true,"sendKeyStrategy":"grouped","newCommandTim...
WARN BaseDriver The following capabilities were provided, but are not recognized by appium: app, showIOSLog, sendKeyStrategy, bundleId.
info BaseDriver Session created with session id: f2403b77-33bd-4fc6-b8c3-493ab2a5db86
info WebDriverAgent-driver Determining device to run tests on
info WebDriverAgent-driver udid not provided, using desired caps to create a new sim
info iOSSim Constructing iOS simulator for Xcode version 7.3.1
info WebDriverAgent-driver created simulator 97040B57-359D-49A2-8ACB-45B6A76E08DC. Booting it up
dbug WebDriverAgent-driver Checking whether app is actually present
ERR! WebDriverAgent-driver Error: Could not find app at URL_TO_ZIP_FILE
ERR! WebDriverAgent-driver     at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
ERR! WebDriverAgent-driver     at WebDriverAgentDriver.checkAppPresent$ (lib/driver.js:144:11)
ERR! WebDriverAgent-driver     at tryCatch (/Users/parks169/code/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
ERR! WebDriverAgent-driver     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/parks169/code/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
ERR! WebDriverAgent-driver     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/parks169/code/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
ERR! WebDriverAgent-driver     at GeneratorFunctionPrototype.invoke (/Users/parks169/code/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
```

Verified the URL for the zip file is valid.

NodeJS 6.1.0
Appium Java client 3.4.1
XCUITest driver @ commit e39444d

**Comment by imurchie** [comment]
Zip files are now supported.
