### ISSUE TITLE
Test fails with simctl error

### ISSUE THREAD

**Issue by hoseokchoi** [appium/appium-xcuitest-driver#77]
Hi, I'm trying appium-xcuitest-driver with python-client.
Test fails with an error `[Error: simctl error running 'create': Invalid runtime: undefined]` but I can't figure out what's wrong. I just cloned this repository and installed it using npm.

```
info HTTP <-- POST /wd/hub/session 500 169 ms - 194 
info HTTP --> POST /wd/hub/session {"requiredCapabilities":{},"desiredCapabilities":{"deviceName":"iPhone 6","app":"XXXXXX.app","platformName":"iOS","autoAcceptAlerts":true,"processArguments":{"environment":{"foo":"BAR"},"arguments":[]}}}
info MJSONWP Calling XCUITestDriver.createSession() with args: [{"deviceName":"iPhone 6","...
info BaseDriver Session created with session id: 284d671f-6e64-4d20-8d87-4f9955cf5014
info XCUITest Simluator udid not provided, using desired caps to create a new simulator
ERR! simctl Error: simctl error running 'create': Invalid runtime: undefined
ERR! simctl     at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
ERR! simctl     at simCommand$ (lib/simctl.js:22:11)
ERR! simctl     at tryCatch (/.../appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
ERR! simctl     at GeneratorFunctionPrototype.invoke [as _invoke] (/.../appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
ERR! simctl     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/.../appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
ERR! simctl     at GeneratorFunctionPrototype.invoke (/.../appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
ERR! simctl     at run (/.../appium-xcuitest-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:108:47)
ERR! simctl     at /.../appium-xcuitest-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:119:28
ERR! simctl     at flush (/.../appium-xcuitest-driver/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
ERR! simctl     at nextTickCallbackWith0Args (node.js:420:9)
ERR! simctl     at process._tickCallback (node.js:349:13)
ERR! simctl  [Error: simctl error running 'create': Invalid runtime: undefined]
```

**Comment by imurchie** [comment]
You need to provide a `platformVersion` capability or else the system does not know what version of sim to use/create.

**Comment by HasaanAli** [comment]
Answer above worked but it would be better if it tells proper error like "platformVersion is not specified". :/
**Read For Improvement Purpose**
(Seeing that this question is answered before release of v1.6.0), When I ran _arc_ command without specifying platformVersion, the server said "_No platformVersion specified. Using latest version '10.0'_". But moving further, it threw this(questioned above) _simctl error_ . Whereas specifically adding platformVersion = "10.0" in my appium.txt worked perfectly without any error and launched the app.
